=== oslokommune/sarepta-standarder/meta/Metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="StandardMetadata">
		<xs:annotation>
			<xs:documentation>Definisjon av metadata knyttet til en standard</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Navn" type="xs:string">
					<xs:annotation>
						<xs:documentation>Standardens navn</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Emne" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Hvilket område standarden tilhører. Definert av referansekatalogen</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Versjon" type="xs:string">
					<xs:annotation>
						<xs:documentation>Standardens versjon</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Identifikator" type="xs:string">
					<xs:annotation>
						<xs:documentation>Unik identifikator for denne standarden for denne utgiveren</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Utgivelsesdato" type="xs:date">
					<xs:annotation>
						<xs:documentation>Dato for når standarden ble utgitt.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Statusdato" type="xs:date" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Dato for når standardens status sist ble oppdatert.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Utgiver" type="xs:string">
					<xs:annotation>
						<xs:documentation>Navn på organisasjonen som utgir standarden</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Status">
					<xs:annotation>
						<xs:documentation>Angir om standarden er "til utprøving", mfl. Tatt fra REUMS + utgått</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Under planlegging"/>
							<xs:enumeration value="Til utprøving"/>
							<xs:enumeration value="Til høring"/>
							<xs:enumeration value="Til utbredelse"/>
							<xs:enumeration value="Utgått"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="StatusReferansekatalog" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Status for standardens oppføring i referansekatalogen. Oppgis kun for standarder som inngår i referansekatalogen</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Under utprøving"/>
							<xs:enumeration value="Under innfasing"/>
							<xs:enumeration value="Aktiv"/>
							<xs:enumeration value="Under utfasing"/>
							<xs:enumeration value="Utgått"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Erstatter" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Identifikator til den eller de standardene denne erstatter</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ErstattetAv" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Identifikator til den eller de standardene som erstatter denne</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ProfilAv" minOccurs="0" type="xs:string">
					<xs:annotation>
						<xs:documentation>Identifikator til en standard som denne er en profil av.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Maalgruppe" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Målgruppen(e) til standarden. Kilde: Referansekatalogen</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Standardtekster" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Tekstdokument som definerer en standard</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Standardtekst" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Skjemaer" minOccurs="0">
					<xs:annotation>
						<xs:documentation>XML-skjema</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Skjema" type="Skjemareferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Felleskomponenter" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Gjenbrukbare komponenter som benyttes av flere standarder. Typisk felles XML-skjema</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Felleskomponent" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Modellfiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Modell som beskriver informasjonsstrukturen i standarden, f eks en UML-modell.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Modell" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Visningsfiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Fil som bestemmer hvordan innholdet i en melding skal presenteres, f eks en xslt-fil.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Visningsfil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Testmateriell" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Testmateriell.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Testfil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Eksempler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Eksempler som viser bruk av standarden</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Eksempel" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="RelaterteFiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Andre filer som er relevante for bruk av standarden</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="RelatertFil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="definisjonVersjon" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Filreferanse">
		<xs:annotation>
			<xs:documentation>Referanse til en lokal eller global fil</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Beskrivelse" type="xs:string" minOccurs="0"/>
			<xs:element name="Referanse" type="xs:anyURI"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Skjemareferanse">
		<xs:annotation>
			<xs:documentation>Referanse til skjemafil</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="Filreferanse">
				<xs:sequence>
					<xs:element name="Namespace" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== oslokommune/sarepta-standarder/meta/E-resept-SLV og reseptformidler/SLVOgReseptformidler-2.5-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Temaer>
		<Tema>E-reseptmeldinger</Tema>
	</Temaer>
	<Navn>Mellom Statens legemiddelverk og Reseptformidleren m.fl.</Navn>
	<Utgitt>07/2018</Utgitt>
	<Ansvarlig>Direktoratet for e-helse</Ansvarlig>
	<Status>Fastsatt som standard</Status>
	<MerInformasjon>
		<Informasjon>
			<Beskrivelse>Om bruk og målgrupper</Beskrivelse>
			<Referanse>https://ehelse.no/referansekatalog/referansekatalogen-for-ehelse#E-reseptmeldinger</Referanse>
		</Informasjon>
	</MerInformasjon>

	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>eResept – Verify-melding (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/eResept-MV-2013-08-16.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>eResept - M3 Anmodning om søknad til SLV - M14 Søknadtil SLV - M15 Søknadssvar fra SLV (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/R1108-eResept-M3-M14-M15-2013-04-16.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>eResept - Utleveringsrapporter M6, M8, M8.1, M10 og M20 (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/R1308-eResept-M6-M8-M81-M10-M20-2015-09-22.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>eResept – M30 FEST og Forskrivning (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/R1808-eResept-M30-2013-10-08.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>eResept – M30 FEST og Forskrivning (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/R1808-eResept-M30-2014-12-01.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>
	
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/eresept/M3-M14-M15/ER-M14-2008-12-12.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m14/2008-12-12</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M3-M14-M15/ER-M15-2006-10-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m15/2006-10-06</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M6-M8-M81-M10-M20/ER-M10-2013-10-08.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m10/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M6-M8-M81-M10-M20/ER-M20-2013-10-08.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m20/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M30/ER-M30-2013-10-08.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m30/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M30/ER-M30-2013-10-08-loose.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m30/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M30/ER-M30-2014-12-01.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m30/2014-12-01</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/M30/ER-M30-2014-12-01-loose.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m30/2014-12-01</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/MV/ER-MV-2013-08-16.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/mv/2013-08-16</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/MV/ER-MV-2017-01-01.xsd</Referanse>
			<Namespace>http://ehelse.no/xmlstds/eresept/mv/2017-01-01</Namespace>
		</Skjema>
	</Skjemaer>
	<Felleskomponenter>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/kith-base64.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	<Visningsfiler>
		<Visningsfil>
			<Referanse>visningsfil/eresept/m15/m15-2html-v2.5.xsl</Referanse>
		</Visningsfil>
	</Visningsfiler>
	<Eksempler>
		
		<Eksempel>
			<Referanse>eksempel/eresept/ER-M14-2008-12-12-eksempel1.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/eresept/ER-M14-2008-12-12-eksempel1-msghead.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/eresept/ER-M15-2006-10-06-eksempel1-msghead.xml</Referanse>
		</Eksempel>
	</Eksempler>
	
	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Applikasjonskvittering v 1.0</Beskrivelse>
			<Referanse>kravdokument/applikasjonskvittering/HIS_80415_2004 AppRec v1.0 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Notat til bruk av kith-base.xsd</Beskrivelse>
			<Referanse>relaterteFiler/eresept/NOTAT-kith-base64.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Hodemelding v 1.2</Beskrivelse>
			<Referanse>kravdokument/hodemelding/HIS_80601_2006-Hodemelding-v12 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Datatyper v 1.1</Beskrivelse>
			<Referanse>kravdokument/DatatyperTilBrukVedMeldingsutveksling/HIS_80117_2002_Datatyper_v1.1 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Notat - Opplysninger om signerende helsepersoenell i meldinger fra Helseforetak til NAV og Reseptformidleren</Beskrivelse>
			<Referanse>relaterteFiler/eresept/Signerende_HelsepersonellSykmelding-eResept-notat.pdf</Referanse>
		</RelatertFil>
	</RelaterteFiler>	
	
	
</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/Teststandard/Teststandard-1.0-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Teststandard</Navn>
	<Versjon>1.0</Versjon>
	<Identifikator>BG-1234</Identifikator>
	<Utgivelsesdato>2016-02-12</Utgivelsesdato>
	<Utgiver>Direktoratet for e-helse</Utgiver>
	<Status>Utgått</Status>
	<StatusReferansekatalog>Utgått</StatusReferansekatalog>
	<ErstattetAv>ingenting</ErstattetAv>
	<Standardtekster>
		<Standardtekst>
			<Beskrivelse>En standardtekst</Beskrivelse>
			<Referanse>standardtekst/FEILTeststandard/test.txt</Referanse>
		</Standardtekst>
	</Standardtekster>
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/FEILTeststandard/test.txt</Referanse>
			<Namespace>http://www.kith.no/xmlstds/test/9999-01-01</Namespace>
		</Skjema>
	</Skjemaer>
	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/FEILfelleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	<Modellfiler>
		<Modell>
			<Beskrivelse>En modell</Beskrivelse>
			<Referanse>informasjonsmodell/FEILTeststandard/test.txt</Referanse>
		</Modell>
	</Modellfiler>
	<Visningsfiler>
		<Visningsfil>
			<Beskrivelse>En visningsfil</Beskrivelse>
			<Referanse>visningsfil/FEILTeststandard/test.txt</Referanse>
		</Visningsfil>
	</Visningsfiler>
		<Testmateriell>
		<Testfil>
			<Beskrivelse>En testfil</Beskrivelse>
			<Referanse>test/FEILTeststandard/test.txt</Referanse>
		</Testfil>
	</Testmateriell>
	<Eksempler>
		<Eksempel>
			<Referanse>eksempel/FEILTeststandard/test.txt</Referanse>
		</Eksempel>
	</Eksempler>
	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Hodemleding TEST</Beskrivelse>
			<Referanse>eksempel/FEILTeststandard/test.txt</Referanse>
		</RelatertFil>
	</RelaterteFiler>
</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/EBXML rammeverk/EBXMLrammeverk-1.1-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>ebXML Rammeverk</Navn>
	<Versjon>1.1</Versjon>
	<Identifikator>HIS 1037:2011</Identifikator>
	<Utgitt>06/2011</Utgitt>
	<Ansvarlig>Direktoratet for e-helse</Ansvarlig>
	<Status>Fastsatt som standard</Status>	
	<MerInformasjon>
		<Informasjon>
			<Beskrivelse>ebXML Rammeverk 1.1</Beskrivelse>
			<Referanse>http://ehelse.no/HIS1037-2011</Referanse>
		</Informasjon>
	</MerInformasjon>


	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>ebXML Rammeverk 1.1 (PDF)</Beskrivelse>
			<Referanse>kravdokument/EBXMLrammeverk/HIS 1037_2011 Rammeverk for meldingsutveksling v1.1 -korrigert.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>
	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Veiledning til riktig implementasjon og bruk av ebXML (PDF)</Beskrivelse>
			<Referanse>relaterteFiler/EBXMLrammeverk/HISD 1171_2017 Veiledning til riktig implementasjon og bruk av ebXML v1.0.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Validering av ebXML-meldinger (PDF)</Beskrivelse>
			<Referanse>relaterteFiler/EBXMLrammeverk/HISD 1172_2017 Validering av ebXML-meldinger.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Implementasjonsguide API for bruk av kommunikasjonsparametere (PDF)</Beskrivelse>
			<Referanse>relaterteFiler/EBXMLrammeverk/HISD_1177_2017 Implementasjonsguide API for bruk av kommunikasjonsparametere.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Service, Action og Role i ebXML-konvolutten (PDF)</Beskrivelse>
			<Referanse>relaterteFiler/EBXMLrammeverk/HISD_1209_2018 Service_Action_og_Role i ebXML-konvolutten.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Overvåkning av meldingsversjoner i ebXML (PDF)</Beskrivelse>
			<Referanse>relaterteFiler/EBXMLrammeverk/HISD_1210_2018 Overvåkning av meldingsversjoner i ebXML.pdf</Referanse>
		</RelatertFil>
	</RelaterteFiler>

</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/Pasientens fastlege/HELFOpasientensFastlege-1.0-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Pasientens fastlege</Navn>
	<Versjon>1.0</Versjon>
	<Identifikator>HIS 1022:2010</Identifikator>
	<Utgivelsesdato>2010-02-01</Utgivelsesdato>
	<Utgiver>Helsedirektoratet</Utgiver>
	<Status>Til utbredelse</Status>
	<StatusReferansekatalog>Aktiv</StatusReferansekatalog>
	<Standardtekster>
		<Standardtekst>
			<Beskrivelse>Forespørsel om fastlege. Informasjonsmodell og XML meldingsbeskrivelse (PDF)</Beskrivelse>
			<Referanse>standardtekst/HELFOPasientensFastlege/HIS_1022_2010_NAV-Fastlege-2010-02-01.pdf</Referanse>
		</Standardtekst>
	</Standardtekster>
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/HELFOPasientensFastlege/NAV-Fastlege-2010-02-01.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/nav/fastlege/2010-02-01</Namespace>
		</Skjema>
	</Skjemaer>
	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>XML-skjema for Hodemelding</Beskrivelse>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc</Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Referansekatalog-oppføring for Forespørsel om fastlege (HIS 1022:2010)</Beskrivelse>
			<Referanse>https://ehelse.no/Sider/Foresp%c3%b8rsel-om-fastlege--Informasjonsmodell-og-XML-meldingsbeskrivelse-%e2%80%93-HIS-10222010.aspx</Referanse>
		</RelatertFil>
	</RelaterteFiler>
</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/Henvisning/Henvisning-1.0-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Henvisning</Navn>
	<Versjon>1.0</Versjon>
	<Identifikator>HIS 80517:2005</Identifikator>
	<Utgivelsesdato>2005-07-01</Utgivelsesdato>
	<Utgiver>Helsedirektoratet</Utgiver>
	<Status>Til utbredelse</Status>
	<StatusReferansekatalog>Under utfasing</StatusReferansekatalog>
	<ErstattetAv>HIS 80517:2014</ErstattetAv>
	<Maalgruppe>Spesialisthelsetjenesten</Maalgruppe>
	<Maalgruppe>Kommuner</Maalgruppe>
	<Maalgruppe>Fastleger</Maalgruppe>
	<Standardtekster>
		<Standardtekst>
			<Beskrivelse>Henvisning. Informasjonsmodell og XML meldingsbeskrivelse (PDF)</Beskrivelse>
			<Referanse>standardtekst/Henvisning/HIS_80517_2005_Henvisning_v1.0.pdf</Referanse>
		</Standardtekst>
		<Standardtekst>
			<Beskrivelse>Henvisning. Informasjonsmodell og XML meldingsbeskrivelse (DOC)</Beskrivelse>
			<Referanse>standardtekst/Henvisning/HIS_80517_2005_Henvisning_v1.0.doc</Referanse>
		</Standardtekst>
	</Standardtekster>
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/Henvisning/FEIL_Henvisning-v1.0.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/Henvisning/2005-07-08</Namespace>
		</Skjema>
	</Skjemaer>
	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc </Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Container for Base64-kodet innhold</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith-base64.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	<Modellfiler>
		<Modell>
			<Beskrivelse>Rational Rose modellfil</Beskrivelse>
			<Referanse>informasjonsmodell/Henvisning/Henvisning-v1.0-BUP-revisjon.mdl</Referanse>
		</Modell>
	</Modellfiler>
	<Visningsfiler>
		<Visningsfil>
			<Referanse>visningsfil/Henvisning/henvisning2html-v1.0.xsl</Referanse>
		</Visningsfil>
	</Visningsfiler>
	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Den gode henvisning - Medisinsk-faglig innhold i henvisninger</Beskrivelse>
			<Referanse>https://ehelse.no/Sider/Medisinsk-faglig-innhold-i-henvisninger-–-«Den-gode-henvisning»---HIS-803222003.aspx</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Krav til tjenestebasert adressering</Beskrivelse>
			<Referanse>https://ehelse.no/Sider/Krav-til-tjenestebasert-adressering-(HIS-11532015.aspx</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Referanse>https://ehelse.no/Sider/Retningslinjer-endring,-kansellering,-tillegg-og-historikk---HISD-11542013.aspx</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Datatyper til bruk ved meldingsutveksling</Beskrivelse>
			<Referanse>https://ehelse.no/Sider/Datatyper-til-bruk-ved-meldingsutveksling-mv-–-HIS-801172002.aspx</Referanse>
		</RelatertFil>
	</RelaterteFiler>
</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/Henvisning/Henvisning-1.1-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Henvisningsmelding</Navn>
	<Versjon>1.1</Versjon>
	<Identifikator>HIS 80517:2014</Identifikator>
	<Utgitt>02/2014</Utgitt>

	<Referansekatalogen>
		<Beskrivelse>Henvisningsmelding 1.1 (HIS 80517:2014)</Beskrivelse>
		<Referanse>https://ehelse.no/Sider/Henvisning--Informasjonsmodell-og-XML-meldingsbeskrivelse-%E2%80%93-HIS-805172014.aspx</Referanse>
	</Referansekatalogen>

	<Status>Fastsatt som standard</Status>

	<ForrigeVersjon>HIS 80517:2005</ForrigeVersjon>
	
	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>Henvisning. Informasjonsmodell og XML meldingsbeskrivelse (PDF)</Beskrivelse>
			<Referanse>kravdokument/henvisning/HIS_80517_2014_Henvisning_v1-1-2014-02-13.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>
	
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/henvisning/Henvisning-v1.1.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/Henvisning/2012-02-15</Namespace>
		</Skjema>
	</Skjemaer>
	
	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc</Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Container for Base64-kodet innhold</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith-base64.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	
	<Visningsfiler>
		<Visningsfil>
			<Referanse>visningsfil/henvisning/v1.1/henvisning-v1_1-2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Felleskomponent for alle visningsfiler: KITH-visning.css</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/KITH-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: base64decoder.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/base64decoder.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: base64-konverterer.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/base64-konverterer.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler:cave2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/cave2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler:datamap.xml</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/datamap.xml</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-cave2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-cave2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-journalnotat2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-journalnotat2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-legemiddel2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-legemiddel2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: funksjoner.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/funksjoner.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: journalnotat2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/journalnotat2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kodeverk.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kodeverk.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kodeverk2template.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kodeverk2template.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kritiskInfo2html-v2.5.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kritiskInfo2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: legemiddel2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/legemiddel2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: meldingshode2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/meldingshode2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: poKomponent2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/poKomponent2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): date-time.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/date-time.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): stdlib.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/stdlib.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): string.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/string.xsl</Referanse>
		</Visningsfil>
	</Visningsfiler>
	
</StandardMetadata>
