=== oslokommune/sarepta-standarder/meta/Metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="StandardMetadata">
		<xs:annotation>
			<xs:documentation>Definisjon av metadata knyttet til en standard</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Navn" type="xs:string">
					<xs:annotation>
						<xs:documentation>Standardens navn</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Emne" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Hvilket område standarden tilhører. Definert av referansekatalogen</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Versjon" type="xs:string">
					<xs:annotation>
						<xs:documentation>Standardens versjon</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Identifikator" type="xs:string">
					<xs:annotation>
						<xs:documentation>Unik identifikator for denne standarden for denne utgiveren</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Utgivelsesdato" type="xs:date">
					<xs:annotation>
						<xs:documentation>Dato for når standarden ble utgitt.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Statusdato" type="xs:date" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Dato for når standardens status sist ble oppdatert.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Utgiver" type="xs:string">
					<xs:annotation>
						<xs:documentation>Navn på organisasjonen som utgir standarden</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Status">
					<xs:annotation>
						<xs:documentation>Angir om standarden er "til utprøving", mfl. Tatt fra REUMS + utgått</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Under planlegging"/>
							<xs:enumeration value="Til utprøving"/>
							<xs:enumeration value="Til høring"/>
							<xs:enumeration value="Til utbredelse"/>
							<xs:enumeration value="Utgått"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="StatusReferansekatalog" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Status for standardens oppføring i referansekatalogen. Oppgis kun for standarder som inngår i referansekatalogen</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Under utprøving"/>
							<xs:enumeration value="Under innfasing"/>
							<xs:enumeration value="Aktiv"/>
							<xs:enumeration value="Under utfasing"/>
							<xs:enumeration value="Utgått"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Erstatter" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Identifikator til den eller de standardene denne erstatter</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ErstattetAv" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Identifikator til den eller de standardene som erstatter denne</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ProfilAv" minOccurs="0" type="xs:string">
					<xs:annotation>
						<xs:documentation>Identifikator til en standard som denne er en profil av.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Maalgruppe" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Målgruppen(e) til standarden. Kilde: Referansekatalogen</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Standardtekster" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Tekstdokument som definerer en standard</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Standardtekst" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Skjemaer" minOccurs="0">
					<xs:annotation>
						<xs:documentation>XML-skjema</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Skjema" type="Skjemareferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Felleskomponenter" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Gjenbrukbare komponenter som benyttes av flere standarder. Typisk felles XML-skjema</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Felleskomponent" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Modellfiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Modell som beskriver informasjonsstrukturen i standarden, f eks en UML-modell.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Modell" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Visningsfiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Fil som bestemmer hvordan innholdet i en melding skal presenteres, f eks en xslt-fil.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Visningsfil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Testmateriell" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Testmateriell.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Testfil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Eksempler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Eksempler som viser bruk av standarden</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Eksempel" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="RelaterteFiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Andre filer som er relevante for bruk av standarden</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="RelatertFil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="definisjonVersjon" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Filreferanse">
		<xs:annotation>
			<xs:documentation>Referanse til en lokal eller global fil</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Beskrivelse" type="xs:string" minOccurs="0"/>
			<xs:element name="Referanse" type="xs:anyURI"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Skjemareferanse">
		<xs:annotation>
			<xs:documentation>Referanse til skjemafil</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="Filreferanse">
				<xs:sequence>
					<xs:element name="Namespace" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== oslokommune/sarepta-standarder/meta/Medisinsk vurdering av arbeidsmulighet - Sykmelding/Sykmelding1.0-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Medisinsk vurdering av arbeidsmulighet/sykmelding</Navn>
	<Versjon>1.0</Versjon>
	<Identifikator>HIS 80803:2013</Identifikator>
	<Utgitt>03/2013</Utgitt>
	<Utgiver>Helsedirektoratet</Utgiver>

	<Referansekatalogen>
		<Beskrivelse>Medisinsk vurdering av arbeidsmulighet/sykmelding (HIS 80803:2013)</Beskrivelse>
		<Referanse>https://ehelse.no/Sider/Vurdering-av-arbeidsmulighet--sykmelding--Informasjonsmodell-og-XML-meldingsbeskrivelse-–-HIS-808032013.aspx</Referanse>
	</Referansekatalogen>

	<Status>Utgått</Status>

	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>•Vurdering av arbeidsmulighet / sykmelding. Informasjonsmodell og XML meldingsbeskrivelse (PDF)</Beskrivelse>
			<Referanse>kravdokument/NAVSykmelding/HIS_80803_2013-NAV-Sykmelding-2013-03-08.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>

	<Skjemaer>
		<Skjema>
			<Referanse>skjema/NAVSykmelding/NAV-Sykmelding-2011-03-04.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/sykmelding/2011-03-04</Namespace>
		</Skjema>
	</Skjemaer>

	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>XML-skjema for Hodemelding</Beskrivelse>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc</Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>

	<Eksempler>
		<Eksempel>
			<Referanse>eksempel/NAVSykmelding/Eks1-Forstegangs_sykmelding_fra_lege.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/NAVSykmelding/Eks2-Forstegangs_sykmelding_fra_HF.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/NAVSykmelding/Eks3-Forstegangs_sykmelding_fra_tannlege.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/NAVSykmelding/Eks4-Paafolgende_vurdering.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/NAVSykmelding/Eks5-Med_friskmeldingsplan_og_veiledning.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/NAVSykmelding/Eks6-Med_oppfolgningsplan.xml</Referanse>
		</Eksempel>
	</Eksempler>

</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/Legeerklæring ved arbeidsuførhet/LegeerklaringArbeidsuforhet1.0-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Legeerklæring ved arbeidsuførhet</Navn>
	<Versjon>1.0</Versjon>
	<Identifikator>HIS 80805:2008</Identifikator>
	<Utgitt>06/2008</Utgitt>
	<Utgiver>Helsedirektoratet</Utgiver>

	<Referansekatalogen>
		<Beskrivelse>Legeerklæring ved arbeidsuførhet (HIS 80805:2008)</Beskrivelse>
		<Referanse>https://ehelse.no/Sider/Legeerkl%c3%a6ring-ved-arbeidsuf%c3%b8rhet--Informasjonsmodell-og-XML-meldingsbeskrivelse-%e2%80%93-HIS-808052008.aspx</Referanse>
	</Referansekatalogen>

	<Status>Fastsatt som standard</Status>

	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>Legeerklæring ved arbeidsuførhet. Informasjonsmodell og XML meldingsbeskrivelse (GitLab)</Beskrivelse>
			<Referanse>kravdokument/NAVLegeerklæringVedArbeidsuførhet/HIS_80805_2008_NAV-Legeerklaring-2008-06-06.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>

	<Skjemaer>
		<Skjema>
			<Referanse>skjema/NAVLegeerklæringVedArbeidsuførhet/NAV-Legeerklaring-2008-06-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/legeerklaring/2008-06-06</Namespace>
		</Skjema>
	</Skjemaer>

	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>XML-skjema for Hodemelding</Beskrivelse>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc</Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>

	<Eksempler>
		<Eksempel>
			<Referanse>eksempel/NAVLegeerklæringVedArbeidsuførhet/NAV-Legerklaring-2008-06-06-eksempel-1-MsgHead.xml</Referanse>
		</Eksempel>
		<Eksempel>
			<Referanse>eksempel/NAVLegeerklæringVedArbeidsuførhet/NAV-Legerklaring-2008-06-06-eksempel-2-MsgHead.xml</Referanse>
		</Eksempel>
	</Eksempler>

</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/E-resept - Helfo/Helfo-2.5-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Temaer>
		<Tema>E-reseptmeldinger</Tema>
	</Temaer>
	<Navn>Meldinger for Helfo</Navn>
	<Versjon>2.5</Versjon>
	<Ansvarlig>Norsk Helsenett SF</Ansvarlig>
	<Status>Fastsatt som standard</Status>
	<MerInformasjon>
		<Informasjon>
			<Beskrivelse>E-resept dokumentasjon (Confluence)</Beskrivelse>
			<Referanse>https://e-resept.atlassian.net/wiki/spaces/ERDOK/overview</Referanse>
		</Informasjon>
		<Informasjon>
			<Beskrivelse>Bruk av standardene (Referansekatalogen for e-helse)</Beskrivelse>
			<Referanse>https://ehelse.no/standarder/om-standardisering-i-e-helse/referansekatalogen-for-e-helse#E-reseptmeldinger</Referanse>
		</Informasjon>
	</MerInformasjon>
	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>M1 Resept og M21 Ekspederingsanmodning (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/R0908-eResept-M1-M21-2013-10-08.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>M18,M22,M23 Oppgjørskrav og utbetaling (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/R1508-eResept-M18-M22-M23-2013-04-16.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>M2 Søknad om individuell stønad til Helfo (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/HIS 3001_2018 M2 Søknad om individuell stønad til Helfo.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>M12 Svar på søknad om individuell stønad til Helfo (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/HIS 3002_2018 M12 Søknadssvar Individuell søknad om stønad til Helfo.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>
	
	<Skjemaer>
			<Skjema>
			<Referanse>skjema/eresept/ER-M1-2013-10-08.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m1/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M2-2017-12-01.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m2/2017-12-01</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M12-2017-12-01.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m12/2017-12-01</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M18-2013-04-16.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m18/2013-04-16"</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M22-2006-10-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m22/2006-10-06"</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M23-2006-10-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m23/2006-10-06"</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-Utlevering-2013-10-08.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/utlevering/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/Forskrivning-2013-10-08.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/forskrivning/2013-10-08</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/Forskrivning-2014-12-01.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01</Namespace>
		</Skjema>
	</Skjemaer>
	<Felleskomponenter>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/kith-base64.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	<Visningsfiler>
		<Visningsfil>
			<Referanse>visningsfil/eresept/m1-2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/eresept/m15-2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/eresept/utlevering-2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<!-- Felles visningsfiler  -->		
		<Visningsfil>
			<Referanse>visningsfil/hodemelding/v1.2/Hodemelding2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/base64.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/base64_binarydatamap.xml</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/base64decoder.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/datamap.xml</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/eh-komponent2.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/funksjoner.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/kodeverk.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/kritiskInfo2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/meldingshode2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/KITH-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/smooth-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/ehelse-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/SourceForge/date-time.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/SourceForge/stdlib.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/felleskomponenter/SourceForge/string.xsl</Referanse>
		</Visningsfil>
	</Visningsfiler>
	<Eksempler>
	<!-- Utleverer sender oppgjørskrav til Helfo -->
		<Eksempel>
			<Referanse>eksempel/eresept/Utleverer sender oppgjørskrav til Helfo/M1 Resept1.xml</Referanse>
		</Eksempel>			
		<Eksempel>
			<Referanse>eksempel/eresept/Utleverer sender oppgjørskrav til Helfo/M1 Resept2.xml</Referanse>
		</Eksempel>			
		<Eksempel>
			<Referanse>eksempel/eresept/Utleverer sender oppgjørskrav til Helfo/M1 Resept3.xml</Referanse>
		</Eksempel>			
		<Eksempel>
			<Referanse>eksempel/eresept/Utleverer sender oppgjørskrav til Helfo/M18 Oppgjørskrav.xml</Referanse>
		</Eksempel>			
		<Eksempel>
			<Referanse>eksempel/eresept/Utleverer sender oppgjørskrav til Helfo/M22 Oppgjørsresultat.xml</Referanse>
		</Eksempel>			
		<Eksempel>
			<Referanse>eksempel/eresept/Utleverer sender oppgjørskrav til Helfo/M23 Utbetaling.xml</Referanse>
		</Eksempel>
	</Eksempler>
	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Applikasjonskvittering v 1.0</Beskrivelse>
			<Referanse>kravdokument/applikasjonskvittering/HIS_80415_2004 AppRec v1.0 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Vedlegg til meldinger</Beskrivelse>
			<Referanse>kravdokument/VedleggTilMeldinger/HIS_1036_2011-Vedlegg_til_meldinger -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Hodemelding v 1.2</Beskrivelse>
			<Referanse>kravdokument/hodemelding/HIS_80601_2006-Hodemelding-v12 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Datatyper v 1.1</Beskrivelse>
			<Referanse>kravdokument/DatatyperTilBrukVedMeldingsutveksling/HIS_80117_2002_Datatyper_v1.1 -korrigert.pdf</Referanse>
		</RelatertFil>
	</RelaterteFiler>	
</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/E-resept - Nettutleverer/Nettutleverer-2.5-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Temaer>
		<Tema>E-reseptmeldinger - ny versjon</Tema> 
	</Temaer>
	<Navn>Nettutleverer</Navn>
	<Versjon>2.5</Versjon>
	<Utgitt>07/2018</Utgitt>
	<Ansvarlig>Direktoratet for e-helse</Ansvarlig>
	<Status>Fastsatt som standard</Status>
	<MerInformasjon>
		<Informasjon>
			<Beskrivelse>Om bruk og målgrupper</Beskrivelse>
			<Referanse>https://ehelse.no/referansekatalog/referansekatalogen-for-ehelse#E-reseptmeldinger</Referanse>
		</Informasjon>
	</MerInformasjon> 

	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>M9NA1 Forespørsel om reseptliste fra nettkunde (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/HIS 3016_2018 M9NA1 Forespørsel om reseptliste fra nettkunde.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>M9NA2 Reseptliste nettkunde (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/HIS 3017_2018 M9NA2 Reseptliste nettkunde.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>M9NA3 Forespørsel om utvidet informasjon på resept fra nettkunde (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/HIS 3018_2018 M9NA3 Forespørsel om utvidet informasjon på resept fra nettkunde.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>M9NA4 Utvidet informasjon om resept nettkunde (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/HIS 3019_2018 M9NA4 Utvidet informasjon på resept fra nettkunde.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>eResept – Verify-melding (PDF)</Beskrivelse>
			<Referanse>kravdokument/eresept/eResept-MV-2013-08-16.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>
	
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/eresept/ER-M9NA1-2016-06-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m9na1/2016-06-06</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M9NA2-2016-10-26.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m9na2/2016-10-26</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M9NA3-2016-06-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m9na3/2016-06-06</Namespace>
		</Skjema>
		<Skjema>
			<Referanse>skjema/eresept/ER-M9NA4-2016-06-06.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/eresept/m9na4/2016-06-06</Namespace>
		</Skjema>
	</Skjemaer>
	<Felleskomponenter>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/kith-base64.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>

	<RelaterteFiler>
		<RelatertFil>
			<Beskrivelse>Applikasjonskvittering v 1.0 </Beskrivelse>
			<Referanse>kravdokument/applikasjonskvittering/HIS_80415_2004 AppRec v1.0 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Notat til bruk av kith-base.xsd </Beskrivelse>
			<Referanse>relaterteFiler/eresept/NOTAT-kith-base64.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Hodemelding v 1.2 </Beskrivelse>
			<Referanse>kravdokument/hodemelding/HIS_80601_2006-Hodemelding-v12 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Datatyper v 1.1 </Beskrivelse>
			<Referanse>kravdokument/DatatyperTilBrukVedMeldingsutveksling/HIS_80117_2002_Datatyper_v1.1 -korrigert.pdf</Referanse>
		</RelatertFil>
		<RelatertFil>
			<Beskrivelse>Notat - Opplysninger om signerende helsepersoenell i meldinger fra Helseforetak til NAV og Reseptformidleren </Beskrivelse>
			<Referanse>relaterteFiler/eresept/Signerende_HelsepersonellSykmelding-eResept-notat.pdf</Referanse>
		</RelatertFil>
	</RelaterteFiler>	
	 
	
</StandardMetadata>
