=== oslokommune/sarepta-standarder/meta/Metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="StandardMetadata">
		<xs:annotation>
			<xs:documentation>Definisjon av metadata knyttet til en standard</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Navn" type="xs:string">
					<xs:annotation>
						<xs:documentation>Standardens navn</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Emne" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Hvilket område standarden tilhører. Definert av referansekatalogen</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Versjon" type="xs:string">
					<xs:annotation>
						<xs:documentation>Standardens versjon</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Identifikator" type="xs:string">
					<xs:annotation>
						<xs:documentation>Unik identifikator for denne standarden for denne utgiveren</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Utgivelsesdato" type="xs:date">
					<xs:annotation>
						<xs:documentation>Dato for når standarden ble utgitt.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Statusdato" type="xs:date" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Dato for når standardens status sist ble oppdatert.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Utgiver" type="xs:string">
					<xs:annotation>
						<xs:documentation>Navn på organisasjonen som utgir standarden</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Status">
					<xs:annotation>
						<xs:documentation>Angir om standarden er "til utprøving", mfl. Tatt fra REUMS + utgått</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Under planlegging"/>
							<xs:enumeration value="Til utprøving"/>
							<xs:enumeration value="Til høring"/>
							<xs:enumeration value="Til utbredelse"/>
							<xs:enumeration value="Utgått"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="StatusReferansekatalog" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Status for standardens oppføring i referansekatalogen. Oppgis kun for standarder som inngår i referansekatalogen</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Under utprøving"/>
							<xs:enumeration value="Under innfasing"/>
							<xs:enumeration value="Aktiv"/>
							<xs:enumeration value="Under utfasing"/>
							<xs:enumeration value="Utgått"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Erstatter" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Identifikator til den eller de standardene denne erstatter</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ErstattetAv" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Identifikator til den eller de standardene som erstatter denne</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ProfilAv" minOccurs="0" type="xs:string">
					<xs:annotation>
						<xs:documentation>Identifikator til en standard som denne er en profil av.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Maalgruppe" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Målgruppen(e) til standarden. Kilde: Referansekatalogen</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Standardtekster" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Tekstdokument som definerer en standard</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Standardtekst" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Skjemaer" minOccurs="0">
					<xs:annotation>
						<xs:documentation>XML-skjema</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Skjema" type="Skjemareferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Felleskomponenter" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Gjenbrukbare komponenter som benyttes av flere standarder. Typisk felles XML-skjema</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Felleskomponent" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Modellfiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Modell som beskriver informasjonsstrukturen i standarden, f eks en UML-modell.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Modell" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Visningsfiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Fil som bestemmer hvordan innholdet i en melding skal presenteres, f eks en xslt-fil.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Visningsfil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Testmateriell" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Testmateriell.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Testfil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Eksempler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Eksempler som viser bruk av standarden</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Eksempel" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="RelaterteFiler" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Andre filer som er relevante for bruk av standarden</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="RelatertFil" type="Filreferanse" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="definisjonVersjon" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Filreferanse">
		<xs:annotation>
			<xs:documentation>Referanse til en lokal eller global fil</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Beskrivelse" type="xs:string" minOccurs="0"/>
			<xs:element name="Referanse" type="xs:anyURI"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Skjemareferanse">
		<xs:annotation>
			<xs:documentation>Referanse til skjemafil</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="Filreferanse">
				<xs:sequence>
					<xs:element name="Namespace" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== oslokommune/sarepta-standarder/meta/Henvisning/Henvisning-2.0-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Henvisningsmelding</Navn>
	<Versjon>2.0</Versjon>
	<Identifikator>HIS 80517 Utprøving 2017</Identifikator>
	<Utgitt>02/2017</Utgitt>

	<Status>Til pilotering</Status>
	<ForrigeVersjon>HIS 80517:2014</ForrigeVersjon>
	
	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>Henvisning. Informasjonsmodell og XML meldingsbeskrivelse (GitLab)</Beskrivelse>
			<Referanse>kravdokument/henvisning/HIS_80517_2017 Henvisning 2.0 til utprøving.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>
	
	<Skjemaer>
		<Skjema>
			<Referanse>skjema/henvisning/Henvisning-v2.0.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/henvisning/2014-04-30</Namespace>
		</Skjema>
		<Skjema>
			<Beskrivelse>Komponenter som gjenbrukes i flere ulike Pleie- og omsorgsmeldinger</Beskrivelse>
			<Referanse>skjema/plo/v1.6/poKomponent-v1.6.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/po/poKomponent/2012-04-01</Namespace>
		</Skjema>
	</Skjemaer>
	
	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc</Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Container for Base64-kodet innhold</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith-base64.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>XML-skjema for Hodemelding</Beskrivelse>
			<Referanse>skjema/felleskomponenter/MsgHead-v1_2.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	
	<Visningsfiler>
		<Visningsfil>
			<Beskrivelse>Felleskomponent for alle visningsfiler: KITH-visning.css</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/KITH-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: base64decoder.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/base64decoder.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: base64-konverterer.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/base64-konverterer.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler:cave2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/cave2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler:datamap.xml</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/datamap.xml</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-cave2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-cave2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-journalnotat2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-journalnotat2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-legemiddel2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-legemiddel2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: funksjoner.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/funksjoner.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: journalnotat2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/journalnotat2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kodeverk.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kodeverk.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kodeverk2template.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kodeverk2template.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kritiskInfo2html-v2.5.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kritiskInfo2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: legemiddel2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/legemiddel2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: meldingshode2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/meldingshode2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: poKomponent2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/poKomponent2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): date-time.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/date-time.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): stdlib.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/stdlib.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): string.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/string.xsl</Referanse>
		</Visningsfil>
	</Visningsfiler>	
</StandardMetadata>

=== oslokommune/sarepta-standarder/meta/Dialogmelding/Dialogmelding-1.1-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by eResept (Helsedirektoratet) -->
<StandardMetadata definisjonVersjon="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Metadata.xsd">
	<Navn>Dialogmelding</Navn>
	<Versjon>1.1</Versjon>
	<Identifikator>HIS 80603:2017</Identifikator>
	<Utgitt>02/2017</Utgitt>
	<Utgiver>Direktoratet for e-helse</Utgiver>
	<Referansekatalogen>
		<Beskrivelse>Dialogmelding 1.1 (HIS 80603:2017)</Beskrivelse>
		<Referanse>http://ehelse.no/HIS80603-2017</Referanse>
	</Referansekatalogen>
	<Status>Fastsatt som standard</Status>

	<Kravdokumenter>
		<Kravdokument>
			<Beskrivelse>Dialogmelding v1.1 (GitLab)</Beskrivelse>
			<Referanse>kravdokument/dialogmelding/v11/HIS 80603_2017 Standard for dialogmelding.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>Profil: Digital dialog (GitLab)</Beskrivelse>
			<Referanse>kravdokument/dialogmelding/v11/HIS 1176_2017 Digital dialog Profil av dialogmelding.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>Profil: Helsefaglig dialog (GitLab)</Beskrivelse>
			<Referanse>kravdokument/dialogmelding/v11/HIS 1077_2017 Helsefaglig dialog.pdf</Referanse>
		</Kravdokument>
		<Kravdokument>
			<Beskrivelse>Profil: Status på henvisning (GitLab)</Beskrivelse>
			<Referanse>kravdokument/dialogmelding/v11/HIS_1206-2018 Status på henvisning.pdf</Referanse>
		</Kravdokument>
	</Kravdokumenter>

	<Skjemaer>
		<Skjema>
			<Referanse>skjema/dialogmelding/2013-01-23/dialogmelding-v1.1.xsd</Referanse>
			<Namespace>http://www.kith.no/xmlstds/dialog/2013-01-23</Namespace>
		</Skjema>
	</Skjemaer>

	<Felleskomponenter>
		<Felleskomponent>
			<Beskrivelse>Felles XML-definisjoner for person, helsepersonell, organisasjon etc </Beskrivelse>
			<Referanse>skjema/felleskomponenter/felleskomponent1.xsd</Referanse>
		</Felleskomponent>
		<Felleskomponent>
			<Beskrivelse>Felles datatyper</Beskrivelse>
			<Referanse>skjema/felleskomponenter/kith.xsd</Referanse>
		</Felleskomponent>
	</Felleskomponenter>
	
	<Visningsfiler>
		<Visningsfil>
			<Referanse>visningsfil/dialogmelding/v1.1/Dialog-v1_1-2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Referanse>visningsfil/dialogmelding/v1.1/Dialog-v1_1-2html-forIE.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Felleskomponent for alle visningsfiler: smooth-visning.css</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/smooth-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Felleskomponent for alle visningsfiler: eh-komponent2.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/eh-komponent2.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Felleskomponent for alle visningsfiler: KITH-visning.css</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/KITH-visning.css</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: base64decoder.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/base64decoder.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: base64-konverterer.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/base64-konverterer.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler:cave2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/cave2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler:datamap.xml</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/datamap.xml</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-cave2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-cave2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-journalnotat2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-journalnotat2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: EPJ-legemiddel2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/EPJ-legemiddel2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: funksjoner.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/funksjoner.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: journalnotat2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/journalnotat2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kodeverk.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kodeverk.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kodeverk2template.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kodeverk2template.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: kritiskInfo2html-v2.5.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/kritiskInfo2html-v2.5.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: legemiddel2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/legemiddel2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: meldingshode2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/meldingshode2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler: poKomponent2html.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/poKomponent2html.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): date-time.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/date-time.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): stdlib.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/stdlib.xsl</Referanse>
		</Visningsfil>
		<Visningsfil>
			<Beskrivelse>Funksjonsfil som benyttes for alle visningsfiler (Fra SourceForge): string.xsl</Beskrivelse>
			<Referanse>visningsfil/felleskomponenter/SourceForge/string.xsl</Referanse>
		</Visningsfil>
	</Visningsfiler>
 

</StandardMetadata>
